import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "County Crops | Eastern Shore Farmers Market",
  description: "Digital farmers market on the Eastern Shore of Virginia. Pre-order fresh local produce delivered to your door every Friday and Saturday.",
  openGraph: {
    title: "County Crops | Local Food Delivered",
    description: "Connecting Eastern Shore farms to your neighborhood. Fresh produce, delivered.",
    type: "website",
    url: "https://countycrops.com",
  },
};